### ISSUE TITLE
Get a list of players

### ISSUE THREAD

**Issue by iibykov** [iibykov/cotletico-manager#1]
# Описание задачи Create list of players for every team in 2022 FIFA World Cup
# DoD json file with data format {country: [{player}, {player}...], counrty: [{player}, {player}...]... }. {player} attributes - (name, surname, position, rating, date_of_birth, number, team, statistics)

**Comment by dmitriy-bel** [comment]
> Описание задачи

create list of players for every team in 2022 Fifa WC
